import { NextResponse } from 'next/server'

const BASE_URL = process.env.NEXT_PUBLIC_URL || 'https://chipchain.shop'

export async function GET() {
  const manifest = {
    // ── Account association — proves domain ownership ────────────
    // PLACEHOLDER: these 3 values must come from Base Build's Account
    // Association tool, signed with your owner wallet. See the
    // accompanying setup guide — this cannot be generated by code,
    // it requires an actual wallet signature from you.
    accountAssociation: {
      header: 'REPLACE_WITH_HEADER_FROM_BASE_BUILD_TOOL',
      payload: 'REPLACE_WITH_PAYLOAD_FROM_BASE_BUILD_TOOL',
      signature: 'REPLACE_WITH_SIGNATURE_FROM_BASE_BUILD_TOOL',
    },

    miniapp: {
      version: '1',
      name: 'Chip Chain',
      homeUrl: `${BASE_URL}/play`,
      iconUrl: `${BASE_URL}/branding/icon-1024.png`,
      splashImageUrl: `${BASE_URL}/branding/splash-200.png`,
      splashBackgroundColor: '#1a90d8',

      subtitle: 'The Great British Fry-Off',
      description: 'Serve fish and chips, earn $CHIP onchain, and collect Newspaper Wrap NFTs in this British chippy game built on Base. Live on Base Mainnet now.',
      tagline: 'Serve, earn, collect onchain',

      screenshotUrls: [
        `${BASE_URL}/branding/screenshot1-play.png`,
        `${BASE_URL}/branding/screenshot2-leaderboard.png`,
        `${BASE_URL}/branding/screenshot3-profile-wraps.png`,
      ],

      primaryCategory: 'games',
      tags: ['gaming', 'onchain', 'base', 'nft', 'leaderboard'],

      heroImageUrl: `${BASE_URL}/og-image.png`,
      ogTitle: 'Chip Chain - Live on Base',
      ogDescription: 'Serve fish and chips, earn $CHIP onchain, and climb the leaderboard. Live on Base Mainnet.',
      ogImageUrl: `${BASE_URL}/og-image.png`,

      buttonTitle: 'Play Chip Chain',
    },
  }

  return NextResponse.json(manifest)
}
